from __future__ import annotations
from typing import Protocol,Any
from .models import *

class GitGoblinOracle(Protocol):
    def frontier_batch(self,cursor:str)->ObservationBatch: ...

class DellOracle(Protocol):
    def candidate_snapshot(self,request:dict[str,Any])->tuple[ResourceCandidateSnapshot,DecisionAdvisory|None]: ...

class ForgeExchange(Protocol):
    def assets(self,capability:str)->tuple[CapabilityAssetView,...]: ...
    def execute(self,request:CapabilityExecutionRequest)->InvocationOutcome: ...
    def bind_certificate(self,outcome:InvocationOutcome,certificate:VerificationCertificateRef)->None: ...

class QDWVerifier(Protocol):
    def verify_invocation(self,outcome:InvocationOutcome,work_ref:FederatedRef)->VerificationCertificateRef: ...
